name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - scipy 
  - bottleneck
  - XLsxWriter
  - pyarrow
  - tabulate
  - xlrd
  - xlwt
  - zlib 
  - xarray  
#  - setuptools
#  - wheel  
#  - spyder 
  - matplotlib
  - seaborn
  - numpy >=1.19.1
  - sympy 
  - cvxopt
  - graphviz
  - qgrid
  - rise
#  - jupyter 
  - networkx
  - numba
  - tqdm
  - jupyter_contrib_nbextensions
#  - conda-build
